day17/randomName/randomName/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#home', as: :home
  post '/' => 'home#home', as: :submit
end

day17/randomName/randomName/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

day17/randomName/randomName/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

day17/randomName/randomName/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
      if params[:names] != nil && params[:names] != ""
      names = params[:names].split(',').shuffle
      @winner = names.pop
      end
  end
end

day17/randomName/randomName/app/helpers/application_helper.rb
module ApplicationHelper
end

day17/randomName/randomName/app/helpers/home_helper.rb
module HomeHelper
end

day17/randomName/randomName/app/views/home/home.html.erb
<h1>Random Name Picker</h1>
<!-- create the form
set method to somme name
in the routes, post whatever the name is
and then send it to home # whatever the name is  -->
<div class="">
  Please enter some names separated by a comma
</div>
<%= form_tag submit_path do %>
<div class="">
    <%= label_tag :names %>
    <%= text_area_tag  :names %>
</div>
  <%= submit_tag "Pick a winner" %>
<% end %>

<% if @winner %>
<%= "The random winner is #{@winner}" %>
<% end %>
<!-- <form action="/home" method="post">
  <textarea name="names" rows="4" cols="120"></textarea>
  <div class="">

  </div><input type="button" name="submit" value="Submit">
</form> -->

day17/randomName/randomName/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomName</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Home', home_path %>
    </nav>

    <%= yield %>
  </body>
</html>