amazon/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'home#index', as: :home  # the format is [verb, URL, controller, action] i.e. get , '/' , home, index
  get '/contact' => 'home#contact'  # the format is [verb, URL, controller, action] i.e. get , '/' , home, index
  get '/about' => 'home#about'  # the format is [verb, URL, controller, action] i.e. get , '/' , home, index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/contact_submit' => 'home#contact_submit'

  namespace :admin do
  resources :questions
  # '/index' => 'questions#index'
  end

  # resources :questions do
  # resources :comments
  # #This creates:
  # #(HTTP Verb: post - path: /questions/:id/comments ) ==> comments controller / create action
  # end
  # delete '/questions/:id' => 'questions#destroy'

  get '/faq' => 'home#faq'
  #(HTTP Verb: get - path: /faq ) ==> home controller / faq action
  resources :products do
    get :search, on: :collection
    get :flag, on: :member
    post :approve
    resources :reviews, on: [:create, :destroy]
  end



  get '/products/new' => 'products#new', as: :product_new
  # post '/products' => 'products#create'
  # get '/products' => 'products#index', as: :product
  # get '/products/:id' => 'products#show', as: :product
  # delete 'products/:id' => 'products#destroy'


  resources :questions
  post 'questions/:id/comments' => 'comments#create'
  # (HTTP Verb: post - path: /questions/:id/comments ) ==> comments controller / create action

  # get '/questions/:id'  => 'questions#show'
  # delete '/questions/:id'  => 'questions#destroy'
  # get 'questions/:id/edit' => 'questions#edit'
  # post '/questions/:id/comments' => 'comments#create'
  #(HTTP Verb: delete - path: /questions/:id ) ==> questions controller / destroy action
  #(HTTP Verb: get - path: /questions/:id/edit ) ==> questions controller / edit action
  #(HTTP Verb: get - path: /questions/:id ) ==> questions controller / show action
  # (HTTP Verb: post - path: /questions/:id/comments ) ==> comments controller / create action
  #(HTTP Verb: get - path: /faq ) ==> home controller / faq action


  #:questions refers to the name of the controller
  #


end

amazon/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  { case_sensitive: false, message: "must be unique"}
  # exclusion: in: { %w(apple microsoft sony), message: "%{value} is reserved."}
  validates :price, presence: true
  # uniqueness: {scope: :title}, numericality: {greater_than: 0}
  # validates :description, presence: true, length: {minimum: 10}
  validates :sale_price, presence: true,
  :numericality => {:less_than_or_equal_to => :price}
  validates :hit_count, numericality: {greater_than_or_equal_to: 0}

  # Add a custom methods called `search` to the product model to search for a product with its title or description if it contains a specific word. For instance you should be able to do:
  #
  # Product.search("car")
  #
  # Which should return all the products that have the word car in it's title or description (case insensitive).
  #
  # [Challenge]: Show the products that contain the searched word in their title before the ones that contain the searched word only in the description. For instance, if a product contains the word `car` in its title, it should before a product that only contains the word `car` only in the description.


  def self.search(keyword)
    where(["title ILIKE ? OR description ILIKE ?", "%#{keyword}%", "%#{keyword}%"])
    # Product.where(["title ILIKE ?", "%car%"] || ["description ILIKE ?", "%car%"] )
    # Question.where([“title ILIKE ?”, “%a%”])
    # order + case when
  end

  def self.searchStretch(keyword)
    where(["title ILIKE ?", "%#{keyword}%"]) + where(["description ILIKE ?", "%#{keyword}%"] )
  end

  def on_sale?
    sale_price < price
  end

  # def increment
  #   increment(:hit_count, by = 1)
  # end


  after_initialize :set_defaults
  before_validation :stub_sale_price
  # before_save :titleize_title

  private

  def stub_sale_price
    self.sale_price ||= self.price
  end


  def set_defaults #if you wanna set something in ruby , you have instance variables @viewcount - something , or the other option , if you have attr accessor , you can self.viewcount , that value to something
    #if you wanna set the value of a
    # self.price ||= 1

    self.hit_count ||= 0
  end

  # def titleize_title
  #   self.title.capitalize!
  #   #  = title.titleize if title.present?
  # end
end

amazon/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    # render plain: "created!"
    product_params = params.require(:product).permit([:title, :description, :price, :category_id])
    @product = Product.new product_params
    if @product.save
      # redirect_to question_path({id: @question.id})
      # redirect_to question_path({id: @question})
      redirect_to product_path(@product)
    else
      render :new
    end

  end

  def show
    # session[:hit_count] = @hit_count
    @product = Product.find params[:id]
    # @product.hit_count += 1
    @review = Review.new
    Product.increment_counter(:hit_count, @product[:id])
    # Object.update_attribute(:only_one_field, "Some Value")
  end

  def index
    # render :nothing => true
    @products = Product.order(created_at: :desc)
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to products_path
  end

  def edit
    @question = Question.find params[:id]
  end

  def update
  end


end

amazon/app/helpers/products_helper.rb
module ProductsHelper
end

amazon/app/views/products/index.html.erb
<h1>INDEX</h1>
<div><%= link_to 'Add New Product', product_new_path %>
</div>
<br>
<% @products.each do |p| %>

<%= link_to p.title, product_path(p) %>
<hr />
<% end %>

amazon/app/views/products/new.html.erb
<h1>New Product Form</h1>

<%= form_for @product do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, @categories, :id, :name, :prompt => "Select a category" %>

  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_area :price %>
  </div>


    <%# this will automatically generate a submit button. The label for the button
      will depend on the `@question` variable. If @question is a new instance
      then the label of the button will be `Create #{model name capitalized}`.
      If you're not happy with the label, you can pass the label as a first
      arguement: f.submit 'Create'  %>
  <%= f.submit 'Add Product to DB' %>
<% end %>
<%# we can use f.label and f.text_field to generate a label/text input group
    in this case `title` must be an attribute for the variable you pass to
    form_for which is @question in this case.
    The label will have a`for` attribute that matches the id of the
    generated input field for the title.
    The title input field will have a name attribute that is model_type[field]
    In the example below the `name` attribute for the input field will be:
    question[title].
    The input field will be prepolulated with a value if the @question
    has that attribute value set to something. %>

amazon/app/views/products/show.html.erb
<!-- Show page (url :/products/:id) that displays the product details -->
<h1>Show Product Page</h1>
<!-- Give it a default view -->
<div class="">
<%= "Title: #{@product.title}" %>
</div>
<div class="">
<%= "Category: #{@product.category.name}" %>
</div>
<div class="">
<%= "Description: #{@product.description}" %>
</div>
<div class="">
  <%= "Price: #{number_to_currency(@product.price)}" %>
</div>
<div class="">
  <%= "Sale Price: #{number_to_currency(@product.sale_price)}" %>
</div>
<div class="">
  <%= "Hit count: #{(@product.hit_count)}" %>
</div>

<%= link_to 'delete', product_path(@product), method: :delete, data: {confirm: 'Are you sure?'} %>
<br>


<%= @review.errors.full_messages.join(', ') %>
<br>
<h2>Leave a Review</h2>
<%= form_for [@product, @review] do |f| %>
<div class="">
  <%= f.radio_button :star_count, 1 %> 👍<br>
  <%= f.radio_button :star_count, 2 %> 👍👍 <br>
  <%= f.radio_button :star_count, 3 %> 👍👍👍 <br>
  <%= f.radio_button :star_count, 4 %> 👍👍👍👍 <br>
  <%= f.radio_button :star_count, 5 %> 👍👍👍👍👍 <br>
</div>
<div class="">
  <%= f.label :Review %>
  <%= f.text_area :body %>
</div>
<%= f.submit %>
<% end %>

<h2>⭐All Reviews⭐</h2>

<% @product.reviews.each do |review| %>
<%= review.star_count %>
<%= review.body %>
<%= link_to 'delete', product_review_path(@product, review),
                      method: :delete,
                      data: { confirm: 'are you sure?'} %>
<hr>
<% end %>



<%#  %>