day17/rails/awesome_answers/config/routes.rb
Rails.application.routes.draw do
  #this means when we receive a GET request with '/' URL we invoke the index action within the Home Controller
  #rails convention here is that you just write Home. not Home_controller , rails knows
  get '/' => 'home#index', as: :home  # the format is [verb, URL, controller, action] i.e. get , '/' , home, index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/contact' => 'home#contact'

  post '/contact_submit' => 'home#contact_submit'
  # as: :contact #rails auto-generated a URL helper called contact_path (and contact_url)
end

day17/rails/awesome_answers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

day17/rails/awesome_answers/app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true,
  uniqueness: { case_sensitive: false,
  message: "must be unique"}

#with scope we valudate that the combination of two fields is unique. In the example below
#we are validating that the combination of title/body is unique.

  validates :body, length: {minimum: 5},
            uniqueness: {scope: :title}

  # validates :view_count, numericality: {greater_than_or_equal_to: 0}
# This is the more verbose form of doing validation , to show classes
  validates(:view_count, { numericality: {greater_than_or_equal_to: 0} } )

# assign a private method for something obscure like 'no monkey'
  validate :no_monkey

#callback methods: 
  after_initialize :set_defaults
  before_validation :titleize_title

# scope :recent_ten, lambda { limit(10).order(created_at: :desc)}
#
  def self.recent_ten
    Question.limit(10).order(created_at: :desc)
  end

  private

  def no_monkey
# add an error on the title field
    if title && title.include?('monkey')
      errors.add(:title, 'No monkeys please!')
    end
  end

  def set_defaults #if you wanna set something in ruby , you have instance variables @viewcount - something , or the other option , if you have attr accessor , you can self.viewcount , that value to something
    #if you wanna set the value of a
    self.view_count ||= 0
  end

  def titleize_title
    self.title = title.titleize
  end
end

day17/rails/awesome_answers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

day17/rails/awesome_answers/app/controllers/home_controller.rb
class HomeController < ApplicationController

  #this method is called 'action'
  def index
    #this will render views/homes/index.html.erb and it will Use
    #views/layours/application.html.erb
    #
    # render :index, layout: 'application'
    #rails automatically renders the layout from the appropriate irectory
    #rails takes the second format as the argument ,  in index.html.erb
  end

  def contact
    #if you wanna do something different, you can write
    #index: something else
  end

  def contact_submit
    @name = params[:full_name]
  end
end

day17/rails/awesome_answers/app/helpers/application_helper.rb
module ApplicationHelper
end

day17/rails/awesome_answers/app/helpers/home_helper.rb
module HomeHelper
end

day17/rails/awesome_answers/app/views/home/contact.html.erb
<h1>Contact Us</h1>
<h1>This is blowing my mind right now</h1>
<%# form_tag is a helper method that will generate a form HTML element with POST httml request. The first
argument of the helper method  must be the URL you would like to submit the form to. %>
<%= form_tag contact_submit_path do %>
<div class="">
    <%= label_tag :full_name %>
    <%= text_field_tag :full_name %>
</div>
<div class="">
    <%= label_tag :email %>
    <%= email_field_tag :email %>
</div>
<div class="">
    <%= label_tag :message %>
    <%= text_area_tag  :message %>
</div>
  <%= submit_tag "Contact Us!" %>
<% end %>

day17/rails/awesome_answers/app/views/home/contact_submit.html.erb
<h1>Thanks <%= @name %>for contacting us</h1>

day17/rails/awesome_answers/app/views/home/index.html.erb
<h1>Welcome to Awesome Answers</h1>

day17/rails/awesome_answers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav color="blue">
      <!-- <a href='/'>Home</a> -->
      <%= link_to 'Home', home_path %>
      <!-- ^^ It's advisable to use URL helpers instead of using href's  -->
      <!-- <a href='/contact'>Contact Us</a> -->
      <!-- <%= link_to 'Contact Us', contact_path({something: 'hello world'}) %> -->
      <%= link_to 'Contact Us', contact_path() %>
      <hr>
    </nav>
    <%= yield %>
  </body>
</html>