amazon/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => 'home#index', as: :home  # the format is [verb, URL, controller, action] i.e. get , '/' , home, index
  get '/contact' => 'home#contact'  # the format is [verb, URL, controller, action] i.e. get , '/' , home, index
  get '/about' => 'home#about'  # the format is [verb, URL, controller, action] i.e. get , '/' , home, index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/contact_submit' => 'home#contact_submit'

  namespace :admin do
  resources :questions
  # '/index' => 'questions#index'
  end

  # resources :questions do
  # resources :comments
  # #This creates:
  # #(HTTP Verb: post - path: /questions/:id/comments ) ==> comments controller / create action
  # end
  # delete '/questions/:id' => 'questions#destroy'

  get '/faq' => 'home#faq'
  #(HTTP Verb: get - path: /faq ) ==> home controller / faq action
  resources :products do
    get :search, on: :collection
    get :flag, on: :member
    post :approve
    resources :reviews, on: [:create, :destroy]
  end



  get '/products/new' => 'products#new', as: :product_new
  # post '/products' => 'products#create'
  # get '/products' => 'products#index', as: :product
  # get '/products/:id' => 'products#show', as: :product
  # delete 'products/:id' => 'products#destroy'


  resources :questions
  post 'questions/:id/comments' => 'comments#create'
  # (HTTP Verb: post - path: /questions/:id/comments ) ==> comments controller / create action

  # get '/questions/:id'  => 'questions#show'
  # delete '/questions/:id'  => 'questions#destroy'
  # get 'questions/:id/edit' => 'questions#edit'
  # post '/questions/:id/comments' => 'comments#create'
  #(HTTP Verb: delete - path: /questions/:id ) ==> questions controller / destroy action
  #(HTTP Verb: get - path: /questions/:id/edit ) ==> questions controller / edit action
  #(HTTP Verb: get - path: /questions/:id ) ==> questions controller / show action
  # (HTTP Verb: post - path: /questions/:id/comments ) ==> comments controller / create action
  #(HTTP Verb: get - path: /faq ) ==> home controller / faq action


  #:questions refers to the name of the controller
  #


end

amazon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
  <!-- <a href='/'>Home</a> -->
  <%= link_to 'Home', home_path %>
  |
  <!-- ^^ It's advisable to use URL helpers instead of using href's  -->
  <!-- <a href='/contact'>Contact Us</a> -->
  <!-- <%= link_to 'Contact Us', contact_path({something: 'hello world'}) %> -->
  <%= link_to 'Contact Us', contact_path %>
  |
  <%= link_to 'About Us', about_path %>
  |
  <%= link_to 'Questions', admin_questions_path %>
  |
  <%= link_to 'FAQ', faq_path %>
  |
  <%= link_to 'Products', products_path %>
  <hr>
</nav>
    <%= yield %>
  </body>
</html>